# Cloudflare Pages/Workers configuration
# KV namespace binding for invoices storage
name = "epf-toolbox"
main = "index.js"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "invoices"
id = "5c780b2f878e4c73bd1cf510861d649f"
